docs/archive/UsingWorkerNodeClient
docs/client/using-wn.md
mkdocs.yml

This document gets significantly shorter once you remove pre-pilot references!
Former URL: https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/UsingWorkerNodeClient
Given no users look at these docs, it's not entirely clear this document has to exist.

Migrate the "Using the WN Client" document

---

docs/archive/OSGPKICommandlineClients
docs/common/pki-cli.md
mkdocs.yml

Original URL: https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/OSGPKICommandlineClients
This document was in very poor shape.  It still isn't very good, but we can save a rewrite for a different day.

Migrate the OSG PKI command line client documentation.

---

docs/archive/InstallGlexec
docs/client/glexec.md
mkdocs.yml

Document already existing in a proto-form, but has been touched-up and completed.
Original URL: https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallGlexec

Finish migration of glexec install.

---

docs/archive/InstallWNClientTarball
docs/client/wn-tarball.md
mkdocs.yml

Original URL: https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallWNClientTarball

Migrate the tarball client install to markdown.

---

docs/archive/HelpProcedure
docs/common/help.md
mkdocs.yml

Original URL: https://twiki.opensciencegrid.org/bin/view/Documentation/SiteAdminResources
This page was significantly cleaned up, removing long-defunct help mechanisms.

Migrate the help procedures document to Markdown.

---

docs/security/lcmaps-voms-authentication.md

The example set of mappings in the "Mapping VOs" section did not go from most specific to least specific, causing _all_ GLOW jobs to go to the 'glow' account, even "/GLOW/chtc" jobs. This was confusing: see [GOC #34941](https://ticket.opensciencegrid.org/34941). Fix and add a brief explanation.

Update "Mapping VOs" example

---

docs/worker-node/install-singularity.md

I learned that the EL7.4 kernel is available for pre-EL7.4 systems now in the security updates repository.

Update singularity document to cover pre EL7.4

---

archive/InstallCertAuth
docs/common/ca.md
docs/common/ca_updater.md
docs/common/cert_scripts.md
docs/compute-element/htcondor-ce-overview.md
docs/compute-element/install-htcondor-ce.md
docs/compute-element/job_router.md
docs/data/gridftp.md
docs/index.md
docs/install-overview.md
docs/monitoring/rsv-gwms-tester.md
docs/monitoring/rsv.md
docs/other/gsissh.md
docs/other/install-gwms-frontend.md
docs/security/install-gums.md
docs/security/lcmaps-voms-authentication.md
docs/worker-node/install-cvmfs.md

Ran linkchecker against the webpage generated from the docs repo and fixed 404s it reported. Some of the links were changed to point back to the twiki.

Fix internal links in docs

---

docs/compute-element/install-htcondor-ce.md

https://jira.opensciencegrid.org/browse/SOFTWARE-1796
- empty-slurm still necessary because of the dependence on slurm by
gratia-probe-slurm
- empty-condor still necessary because of the dependence on condor by
htcondor-ce and gratia-probe-condor

Installing empty-{torque,gridengine} are no longer required

---

docs/css/extra.css

The current theme adds a 24px margin to the bottom of all styles except for code-highlight blocks. This makes for an awkward, inconsistent lack-of-space below pre-formatted text.
This has the codehilite class the same as the rest of the documents.
This is the docs repo equivalent to https://github.com/opensciencegrid/technology/pull/339.

Make code-block margins same as print blocks

---

docs/compute-element/install-htcondor-ce.md

I was helping a user set up their CE and was seeing empty stdout until we fixed the location of the spool dir on the wn's

Specify the expected SPOOL dir location on the WNs

---

mkdocs.yml
osgthedocs/404.html

Deprecated as of [0.17.0](https://github.com/mkdocs/mkdocs/blob/master/docs/about/release-notes.md)

Fix deprecated theme_dir specification

---

docs/site-planning.md

Focus currently is deleting absolutely irrelevant / incorrect content and including as many tidbits about OSG as possible.
The result is not pretty - it looks a bit like a wall of words. Diagrams need to be added back, as well as some tables to help illustrate the decision tree.
Have to start somewhere!  There are a lot of things I don't like about this rewrite, but there's less than what we started with.  We at least don't have to put up a warning to readers to not read the document.

Overhaul site planning document.

---

docs/data/external-oasis-repos.md
docs/data/update-oasis.md
mkdocs.yml

The OASIS repository server installation was a bizarre document that was incredibly legalistic and difficult to follow.
This commit is an attempt to simplify the document and rewrite it to better match the language and format of the other OSG software documentation.
I removed as much internal documentation as possible without creating a completely separate document.  If nothing else, I tried to cleanly delineate OSG steps versus non-OSG steps.

Overhaul the OASIS repository document.

---

docs/release/3.3/release-3-3-30.md
docs/release/3.4/release-3-4-5.md

I'd like to be preapproved to merge directly updating the HTCondor release notes when they go out later today.

Update release notes for 3.3.30 and 3.4.5

---

docs/worker-node/install-wn-oasis.md
docs/worker-node/install-wn-tarball.md
docs/worker-node/install-wn.md
docs/worker-node/using-wn.md
mkdocs.yml

This tries to streamline / clarify the introduction of the three WN install variants.  Now, each of them has the same introductory text and mostly have the same header names.
Remove unnecessary / empty header levels.

Rationalize the introduction to the WN installs.

---

docs/data/hadoop-overview.md
docs/data/install-hadoop-2-0-0.md
docs/data/xrootd-overview.md

This commit removes a few unnecessary references to bestman2; I've left all the documentation itself, but just made the HDFS and Xrootd docs a bit less bestman2-centric.
Additionally, this includes a mild cleanup of the Hadoop docs.  Honestly, they are still fairly low-quality - but can be further improved over a series of updates.

Scrub extra references to bestman2.

---

docs/compute-element/htcondor-ce-overview.md
docs/compute-element/install-htcondor-ce.md
docs/index.md

Given that GRAM is pretty far in the rearview mirror, this commit starts to remove references to GRAM.  I left only one remaining, which refers to a specific upgrade path.

Scrub a few remaining GRAM references.

---

osgthedocs/404.html

404 looks good on [docs-itb](https://opensciencegrid.github.io/docs-itb/foobar) vs [production](https://opensciencegrid.github.io/docs/foobar). I originally tried to ignore the offending URLs via linkchecker config but couldn't get that to work because linkchecker is the worst.

Fixup broken 404.html from mkdocs

---

docs/data/external-oasis-repos.md

There's a [bug](https://sft.its.cern.ch/jira/browse/CVM-1446) in cvmfs-2.4.3 and earlier that means we should not yet recommend CVMFS_HASH_ALGORITHM=shake128.

remove CVMFS_HASH_ALGORITHM=shake128 until cvmfs-server-2.4.4

---

docs/compute-element/htcondor-ce-overview.md

Review of HTCondor-CE Overview Document
SOFTWARE-3056
- Added link to Slurm website
- Add Authenticate as well as authorize incoming job
- Move the "Over SSH" section above the other HTCondor-CE configurations
It is more important for new users, probably.
- Change wording from grid job, to "incoming grid job", which is used
and defined before.
- Remove mention of User certificates.  Instead, use the word "client"
and "host" certificates.
- Make links at the bottom full links, rather than just words in the subject.
- Adding email to user-support for SSH HTCondor-CE

Review htcondorce

---

docs/worker-node/install-singularity.md

This is needed soon ahead of an OSG security announcement.

Add instructions to disable network namespaces for unprivileged singularity

---

docs/other/schedd-filebeats.md
mkdocs.yml

This document is for instruction for frontend admins to enable sending the schedd transfer Logs to ES. @djw8605 and I worked on setting this up on osg-connect and it worked. This is basically the same instructions that @LincolnBryant and @jlstephen used to set it up in osg-connect.

Filebeats schedd

---

docs/security/lcmaps-voms-authentication.md

Tell user to disable edg-mkgridmap -- uninstalling it might remove a bunch of metapackages. We can revert this once we've updated the metapackages to drop the requirement.

Disable edg-mkgridmap instead of uninstalling it

---

docs/worker-node/install-singularity.md

- Though noted that no site is ready to run non-setuid singularity,
it was at the top of the document.  I moved it to below the
production instructions.
- Fixed minor typo of the date.
- Added note to install CVMFS in order to validate the installation.

Review of Singularity installation document

---

docs/data/external-oasis-repos.md

It occurred to me that the new section on replacing a server starts rather abruptly and there should be a little transition saying it is only for if a need arises.

Clarify that replacing a server is only for if a need arises

---

docs/compute-element/job-router-recipes.md

The history is a bit weird for this one.  I accidentally committed my changes to the OSG repo's master branch.  Then I reverted it in the master branch.  This pull request reverts that revert.
The original commit is eac9d2d983ce5d6a6718b87d0bc138d14f20ebe2.  
Original commit message:
> Editing the router recipes
>    
> - Adding definitions at the top that are useful throughout
> - Minor edits here and there.
>    
> The page is still accurate.  And the links to HTCondor documentation are to 8.6 version.
This reverts commit 133adee345384db18fab7b1f3942bc72e65c8dec.

Editing the router recipes

---

docs/security/lcmaps-voms-authentication.md

https://opensciencegrid.github.io/docs-itb/security/lcmaps-voms-authentication/#migrating-from-gums
@edquist let me know if I missed anything about how the script is being called
- I'm on the fence about including the output since we generally shy away from it in our docs
- Hopefully the difference between GUMS hosts and clients are clear in the instructions

Add GUMS migration instructions

---

docs/compute-element/install-htcondor-ce.md
docs/data/gridftp.md
docs/security/lcmaps-voms-authentication.md

No longer necessary as of lcmaps-1.6.6-1.9.osg33

Drop instructions for setting 3.3 LCMAPS VOMS env var

---

docs/worker-node/install-singularity.md

The main things:
- Two verification sections are h3's belonging to the priv vs unpriv track instead of h2's
- Used the original wording of the priv vs unpriv note
New layout viewable here: https://opensciencegrid.github.io/docs-itb/worker-node/install-singularity/

Reorganize the Singularity install doc

---

docs/data/gridftp.md

@brianhlin, I had to create a different PR cause I did not know how to remove the commits. I applied all your suggestions. The limits are in the gridftp server so it does not matter the underlying source if its local disk, hdfs or xrootd. I changed the name of the file to make this more obvious

SOFTWARE-2522 (GridFTP limits)Try 2

---

docs/data/bestman-install.md

The LBL links for bestman2 are periodically broken and increasingly less relevant, especially as we near the end of the support.
I don't see much value in including these as a reference (after all, we don't expect to have any new bestman2 services in the next 2.5 months), they can always be found via Google, and they have a noticable cost because of how often they break the CI tests.

Remove LBL links for bestman2 docs.

---

docs/worker-node/install-singularity.md

Although it's not a strict requirement, Singularity in the OSG needs CVMFS for image distribution perhaps this is only true for a few VOs and if that's the case, we can add a disclaimer.

Add CVMFS as a singularity requirement

---

docs/security/user-certs.md

This is a first cut at the doc for SOFTWARE-3260.
@timtheisen or @brianhlin, please offer any suggestions for how to make it better.
Note also that several other places in this user-certs doc reference links to the CLI/osg pki tools stuff, but the link targets don't really seem to have all the expected information.  In any case, I am re-using the osg pki tools links which can be fixed if there is a better place to point them to, in which case the other links in this doc (unrelated to this PR) should also be changed.

Renewing your OSG user certificate / 5yr issue (SOFTWARE-3260)

---

docs/worker-node/install-singularity.md

The given test example for singularity was not working due to a typo &rarr; fixed.

Fixed typo in singularity validation (WN; privileged)

---

docs/other/install-cvmfs-stratum1.md

The reason for the change is that in the future I will be recommending having port 8080 be a copy of port 80 and 8000 for the sake of access via Cloudflare.

Change stratum1 apache port from 8080 to 8081

---

docs/data/update-oasis.md

The previous documentation link pointed at a page which was empty except for a forwarding link.

Tweak language around GOC; fix documentation link

---

docs/security/lcmaps-voms-authentication.md
mkdocs.yml

I'm still not in love with the layout but I think this makes it clearer that there are different instructions for different types of hosts. Plus, all the CE-related config is together now.

Split lcmaps troubleshooting sections

---

docs/compute-element/install-htcondor-ce.md

The HTCondor team suggested that we recommend having the `JOB_QUEUE_LOG` and the `SPOOL` dir on separate file systems in all cases

Review HTCondor-CE install doc, recommend separating JOB_QUEUE_LOG

---

docs/common/registration.md

Tried this out on https://opensciencegrid.org/docs-itb/common/registration/#registering-resource-downtimes. The CI fails because the site's not live yet.

Downtime webform instructions

---

docs/data/stashcache/install-cache.md
docs/data/stashcache/install-origin.md

This is an attempt at cleaning up the StashCache cache installation doc, merging in the corrections from #443.
This goes along with the packaging changes in opensciencegrid/StashCache-Daemon#8.

StashCache docs cleanup

---

docs/data/stashcache/install-cache.md

With this, the three separate systemd management sections are collapsed into one.

Remove redundant management section

---

docs/security/user-certs.md

Part of the reason for this PR is to address issues where angle brackets are showing up as html-escaped versions on the GitHub deployed site

Address some of TimC's comments in #457

---

docs/data/frontier-squid.md

I think this improves on the previous text by not overloading the word "registration"

Clarify round-robin DNS registration

---

docs/other/install-cvmfs-stratum1.md

This is the new recommendation because of [CVM-1655](https://sft.its.cern.ch/jira/browse/CVM-1655).

Update cvmfs stratum 1 instructions to Unset If-Modified-Since request header

---

docs/data/xrootd-authorization.md

/etc/grid-security/xrd/xrdcert{,key}.pem are the de facto standard

Revert the rename of the XRootD cert/key

---

docs/compute-element/job-router-recipes.md
docs/compute-element/troubleshoot-htcondor-ce.md

The latter does the same thing but more safely (i.e., not as a
verbosity modifier for other debug messages). Recommended by TJ.

Change D_FULLDEBUG to D_ALWAYS:2

---

docs/compute-element/troubleshoot-htcondor-ce.md
docs/data/install-hadoop.md
docs/security/lcmaps-voms-authentication.md

There are also some references to `gums_host` in the osg-configure docs and I wasn't sure if they were still relevant so I opted to leave them alone

Cleanup GUMS references

---

docs/compute-element/install-htcondor-ce.md
docs/other/install-gwms-frontend.md

To preserve the port number used by the collector (contacted by the glideins) we decided to use 9618.
Hosts with the Frontend and user collector will have that port already open.
Standalone submit hosts may have only port 9615 open (it was 9615 for GlideinWMS 3.4.0 and earlier).

Updated frontend installation about port requirements for Frontend's submit hosts

---

docs/security/lcmaps-voms-authentication.md

ATLAS/CMS/FNAL are all fine with opportunistic jobs all ending up being mapped to the wildcard user for their VOs

Simplify opportunistic account list

---

docs/compute-element/install-htcondor-ce.md

This reverts commit 71910452a1b422d2b00d0a1e214e404c53e23a69.
This seems to break certain CEs; see tickets:
- https://support.opensciencegrid.org/helpdesk/tickets/6982
- https://support.opensciencegrid.org/helpdesk/tickets/8203

Revert "Add recommendation for a separate job queue location"

---

docs/common/registration.md

Apparently GitHub has publicly available user IDs.
Just something I noticed from https://support.opensciencegrid.org/a/tickets/filters/5000319518

We only need the GitHub account name

---

docs/security/host-certs.md

This keeps biting sites who may direct their central IT to our docs so
we need to make it very clear that the "standard" InCommon RSA CA is
not sufficient for OSG hosts.
@dougbenjamin @hseverini once this gets merged, the emphasis on InCommon IGTF should show up here: https://opensciencegrid.org/docs/security/host-certs/

Emphasize that we only accept InCommon IGTF certs

---

docs/common/yum.md

For EPEL, we provide the full command to download the RPM.  Since we only have 2 downloads now,
be consistent and provide the full command.

Use full commands for downloading OSG RPM

---

docs/common/yum.md

yum install can be pointed at URLs now; using rpm was only required for EL 5.

Use yum install instead of rpm -Uvh

---

docs/other/install-cvmfs-stratum1.md

This instruction has been wrong a long time, but fortunately there aren't very many cvmfs stratum 1s.  I noticed because the BNL stratum 1 had it wrong.

Fix backwards stratum1 squid config

---

docs/other/install-gwms-frontend.md

These color macros don't seem to work so just remove them.

Remove broken formatting from install-gwms-frontend

---

docs/compute-element/install-htcondor-ce.md
docs/security/lcmaps-voms-authentication.md

I thought about modifying the `allowed_vos` instructions to just tell users to use `*` but saw that the instructions mention it's per subcluster. If we change this, we should probably just have the default to `*` in osg-configure and tell people that they should only change it if they need to restrict access

Misc site install exercise fixes

---

docs/data/frontier-squid.md

This refers to the file as of a specific commit, instead of _master_ so the link won't have to be updated if resources get added to or removed from BNL.

Use constant link for topology example

---

docs/worker-node/install-singularity.md

I heard that somebody had a non-container system (a remote desktop application) that also used network namespaces.

Generalize the network namespace warning in install-singularity

---

docs/common/registration.md

Replace broken TWiki highlight macros with a line highlight

---

docs/data/stashcache/vo-data.md

Unlike the rest of the file, namespace permissions use PUBLIC instead of ANY to denote that anyone can access stuff.

Fix Namespace permissions syntax

---

docs/data/stashcache/install-origin.md

Using xrdcp against the origin lets you bypass the redirector, which may be useful in pinning down where the error is occurring.

Add test instructions for directly downloading from the origin

---

docs/other/install-cvmfs-stratum1.md

We found that there were many localhost hits on port 80 going unnecessarily through squid on stratum 1.  Removing this iptables/ip6tables rule eliminates that.

Remove iptables port 80 localhost forward

---

docs/data/xrootd/install-storage-element.md
docs/data/xrootd/overview.md
docs/data/xrootd/xrootd-authorization.md
docs/security/lcmaps-voms-authentication.md

This addresses a few more [XRootD standalone doc issues](https://docs.google.com/document/d/1aXAaGpeKL45AcuYarKOzvHNzMopOEUmd2T08b2bWBYo/edit?usp=sharing) apart from:
- Stuff that should go into `osg-xrootd`
- The XRootD configuration that we tell them to edit in the XRootD AuthZ doc (this seems right to me)
- Host cert vs service cert location

Address some more XRootD standalone issues

---

docs/other/schedd-filebeats.md

filebeat.prospectors is depreciated and now does not work.  replaced with filebeat.inputs

use filebeats inputs

---

docs/release/notes.md

Since we eventually want to move toward rolling releases within a release series, let's ramp up our advertisement of the rolling release repo. We should probably add this same note prominently to each point release page

Add rolling release tip to the release note overview

---

docs/other/configuration-with-osg-configure.md

The note currently shows:
```
[Storage] worker_node_temp = $LOCAL_SCRATCH_DIR
```

Retain multi-line documentation for worker_node_temp var

---

docs/release/3.5/release-3-5-0.md
docs/release/release_series.md

The HTCondor team dropped 8.8.x tags for their documentation. Use
stable instead.

Update HTCondor manual links

---

docs/data/xrootd/install-standalone.md
docs/data/xrootd/install-storage-element.md
docs/data/xrootd/xrootd-authorization.md

Clean up old manual config steps now done by drop-in config.d files brought in by the osg-xrootd-standalone package
Closes: #509

Update XRootD standalone doc to use osg-xrootd (SOFTWARE-3557)

---

docs/common/registration.md

The ticket was for adding site naming recommendations, but I couldn't
find a way to make it make sense without also having instructions for
creating a site.

Add site creation and naming info (SOFTWARE-3894)

---

docs/compute-element/covid-19.md
docs/compute-element/job-router-recipes.md
mkdocs.yml

This is the initial documentation for site admins to accept COVID-19 jobs.
To avoid potential authentication issues, this keeps things separate from VOMS and takes a job router-based approach.

Add initial documentation for accepting COVID-19 pilots.

---

docs/compute-element/covid-19.md

This will help avoid the issue that Mats ran into where he removed his old route name and the job router crashed because of old jobs associated with the old route.
We may actually be able to get rid of the `Only supporting COVID-19` jobs section (or clarify it) since they can just copy the exact same configuration from above that's appropriate for their batch system.

Add COVID-19 routes instead of replacing existing routes

---

mkdocs.yml

So that we can date reviews:
https://opensciencegrid.org/technology/documentation/reviewing-documentation/

Enable the metadata plugin

---

docs/worker-node/install-singularity.md

All OSG VOs can now handle running singularity out of cvmfs when unprivileged user namespaces is available.

Update singularity instructions to strongly recommend only enabling unprivileged

---

docs/common/registration.md

Site naming convention has already been decided upon so this PR adds resource and resource group conventions:
- New resource groups should just be the same as the site name except in the ITB case.
- We discussed using the factory convention for resource names but that creates unnecessarily long site names. We can depend on the already unique site name and tell them to add the service type to the end of it

Clarify topology naming scheme (SOFTWARE-3773)

---

docs/data/stashcache/run-stash-origin-container.md
docs/data/stashcache/run-stashcache-container.md
mkdocs.yml

All of these names are unfortunate but it is what it is.
Though maybe we should just update the doc ToC and headers to:
```
Data
StashCache
Running a Cache in a container
Running an Origin in a container
Install a Cache
Install an Origin
```

Fixup StashCache container names in the ToC and headers

---

docs/data/stashcache/run-stash-origin-container.md

Also, remove the instructions for using a custom authfile. Deployed origins and caches should always get their authfiles from the Topology service. Submitting this as a draft PR since we need to verify that the latest `fresh` tag works as expected

Set default origin export (SOFTWARE-4138)

---

docs/data/stashcache/run-stash-origin-container.md
docs/data/stashcache/run-stashcache-container.md

Labeled as `do-not-merge` because the latest `stable` containers are still using the old config. @efajardo I could use a sanity checking review, though

Document prescribed locations for Stash Cache containers (SOFTWARE-4203)

---

docs/data/xrootd/overview.md

Reword the introductory sentence:
```
The software can be used to _create a export an existing file system_ through multiple protocols, participate in a data federation, or act as a caching service.
```
to be 
```
The software can be used to _create an export of an existing file system_ through multiple protocols, participate in a data federation, or act as a caching service.
```

Fix misplaced articles (typo) within XRootD documentation

---

docs/data/run-frontier-squid-container.md

Squid does not and cannot cache https; that is a man-in-the-middle attack on https.
Also, docker environment variables do not need to be passed in a file, and if they are the file can be anywhere.

Remove reference to https and allow more flexible env settings

---

docs/common/yum.md

- Rename powertools (a CentOS 8.3 change)
- Also have old PowerTools instructions for people not running 8.3+ yet; add admonition about upgrading
Closes #760

Powertools repo name change (SOFTWARE-4440)

---

docs/compute-element/hosted-ce.md

@lmichael107 @jdost321 we wanted to add a step-by-step overview of the Hosted CE process (https://opensciencegrid.atlassian.net/browse/SOFTWARE-4350) so I reorganized and added sections to make the process clearer in the table of contents:
A bunch of other stuff was out of date so this turned into a full doc review, too. Let me know what you think.

Reorganize the Hosted CE request doc (SOFTWARE-4350)

---

docs/common/yum.md
docs/release/3.5/release-3-5-0.md
docs/release/release_series.md
docs/release/updating-to-osg-35.md

This is for both SOFTWARE-4514, and SOFTWARE-4499.
Decided the best way to show that the upcoming repos are release-specific is to mix them in with the other repos in the table.
I also made the "Upcoming Software" section shorter and more to the point.
I also noted 3.6 doesn't have rolling and added the new gpg key to the repo file sample.

Update documentation for info on 3.6 and versioned upcoming repos

---

docs/data/run-frontier-squid-container.md

This is for once the current `fresh` image becomes `stable`, as discussed in [docker-frontier-squid PR #20](https://github.com/opensciencegrid/docker-frontier-squid/pull/20).

Add configuration customization section

---

docs/resource-sharing/os-backfill-containers.md

Noticed by Erik at Purdue
```
[osg@6fee62bc0aff cvmfs]$ cd /cvmfs/cms.cern.ch
bash: cd: /cvmfs/cms.cern.ch: Too many levels of symbolic links
```

Fix an issue with CVMFS mounts

---

docs/data/frontier-squid.md

OSG 3.4 went out of support last year so we should be able to drop this admonition

Remove old release series admonition

---

docs/other/install-cvmfs-stratum1.md

Explicitly list frontier-squid on the yum install line because frontier-awstats no longer requires it.

Update yum install instruction for frontier-squid on stratum1

---

docs/release/3.5/release-3-5-36.md
docs/release/notes.md
docs/release/updating-to-osg-35.md

Added the HTCondor-CE 5 section. Moved HTCondor 8.8.x section before HTCondor 9.0.0 section. (It's a more logical progression.)

Add HTCondor-CE 5 upgrade instructions to OSG-3.5

---

docs/compute-element/hosted-ce.md

The Gridmanager uses `ssh -R` so we should let folks know upfront that remote port forwarding is required

Add remote port forwarding requirement

---

docs/worker-node/install-cvmfs.md

I recently learned a way that allows simplifying the expression setting CVMFS_REPOSITORIES, using `paste` instead of `echo` and `tr` to avoid a trailing comma.

Simplify expression setting CVMFS_REPOSITORIES

---

docs/compute-element/hosted-ce.md

@jeffreynpeterson ran into an issue where the remote site set `MaxSessions=1` that resulted in jobs getting held and the following showed up in the GridmanagerLog (and maybe the hold reason?):
```
mux_client_request_session: session request failed: Session open refused by peer
```

Document the requirement for SSH multiplexing

---

mkdocs.yml

According to
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search,
the search plugin is enabled by default but must be re-added when
other plug-ins are used, like the redirect plugin

Reenable search bar

---

docs/other/install-cvmfs-stratum1.md

The instructions were attempted to be used in Australia and found to be out of date.

Bring cvmfs stratum1 installation instructions up to date

---

docs/data/xrootd/install-standalone.md
docs/data/xrootd/xrootd-authorization.md

Still to do:
- Clarify how user and group mappings work for LCMAPS, vomsxrd, macaroons, and bearer tokens.
- As @matyasselmeci points out, auth references in other docs: https://github.com/opensciencegrid/docs/pull/890#discussion_r726546209

Update XRootD authZ doc for OSG 3.6 (SOFTWARE-4585)

---

docs/data/stashcache/install-cache.md
docs/data/stashcache/install-origin.md
docs/data/stashcache/overview.md
docs/data/stashcache/run-stash-origin-container.md
docs/data/stashcache/run-stashcache-container.md
docs/data/stashcache/vo-data.md

This begins the process of cleaning up the use of the word "StashCache" and replacing it with the "OSDF" terminology (which largely mirrors the OSPool terminology and matches the [Glossary](https://path-cc.io/glossary/) we are trying to develop.

Start of StashCache -> OSDF cleanup.

---

docs/data/xrootd/xrootd-authorization.md

We get it right in the example here https://opensciencegrid.org/docs/data/xrootd/xrootd-authorization/#authorization-database. From Wei:
> XrdVoms maps a typical VOMS attributes 
> 
> VO: atlas   <-- o:
> VO group: /atlas/usatlas <- g:
> 
> You have also have self defined "Special Compound ID"s, for example
> 
> = atlprod o: atlas g: /atlas r: production
> This define "atlprod" as VO "atlas", VO group "/atlas", Role "production"
> 
> x atlprod /xrootd/atlas rwildn
> This define what access privilege "atlprod" has
> 
> The auth file are evaluated in order. The first match will be picked up.

Fix example XRootD groupname auth for VOMS FQANs

---

docs/other/osg-token-renewer.md

I found these incorrect paths in the osg-token-renewer documentation.

Fix incorrect config.ini paths

---

docs/security/tokens/overview.md

- Add info on which VOs can use tokens, and how to tell if tokens have been used
- Tweak text, add additional VOs to the table

Info about pilot jobs and tokens

---

docs/data/stashcache/install-cache.md
docs/data/stashcache/install-origin.md
docs/data/stashcache/overview.md
docs/data/stashcache/run-stash-origin-container.md
docs/data/stashcache/run-stashcache-container.md
docs/data/stashcache/vo-data.md
docs/data/xrootd/install-client.md
docs/data/xrootd/install-cms-xcache.md
docs/data/xrootd/install-standalone.md
docs/data/xrootd/install-storage-element.md
docs/data/xrootd/overview.md
docs/data/xrootd/xrootd-authorization.md

This overrides the `nav` section of mkdocs.yml.
Otherwise the "Installing the OSDF Cache" page would have the title "Install from RPM",
for example.
I did not do all the pages, this is just a starting point.

Make page titles match the first header (for xcache and xrootd pages)

---

docs/data/stashcache/install-cache.md
docs/data/stashcache/install-origin.md
docs/data/stashcache/run-stash-origin-container.md
docs/data/stashcache/run-stashcache-container.md
docs/data/xrootd/install-standalone.md
docs/data/xrootd/xrootd-authorization.md
docs/release/updating-to-osg-36.md

These are fixes to the xrootd auth docs that I found while doing [SOFTWARE-5109](https://opensciencegrid.atlassian.net/browse/SOFTWARE-5109) that I think ought to go in before I can write docs on upgrading caches.

XRootD/XCache (mostly auth) doc fixups

---

docs/compute-element/hosted-ce.md

We have Hosted CEs accepting CLAS12 pilots and they're mapping those credentials to osg14
FYI @bbockelm @jdost321: I figured this was a better solution than getting the existing sites to change their local unix accounts to `osg06`

Update JLab default unix user name

---

docs/data/stashcache/overview.md

This rectifies conflicts that exist between the current https://osg-htc.org/about/osdf and https://opensciencegrid.org/docs/data/stashcache/overview/
It contains a union of suggestions by @bbockelm and Frank W.

Update the Stashcache Overview Page

---

docs/data/stashcache/install-cache.md
docs/data/xrootd/install-standalone.md
docs/data/xrootd/install-storage-element.md
docs/data/xrootd/xrootd-authorization.md
docs/other/configuration-with-osg-configure.md

Part 1 of SOFTWARE-5164: remove references to LCMAPS.
I left alone the compute-element docs (@brianhlin you're working on those?) and the deprecated docs because they will be removed anyway.

Remove LCMAPS info

---

docs/data/xrootd/install-client.md
docs/data/xrootd/install-storage-element.md
docs/security/tokens/using-tokens.md

I left install-gwms-frontend.md alone because that is being handled in #929

Remove GSI information (SOFTWARE-5164)
