docs/install-overview.md, mkdocs.yml
First step in the doc migration
=> Initial installation overview commit

docs/archive/SupportedOperatingSystems, docs/release/supported_platforms.md, mkdocs.yml
Prior location: https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/SupportedOperatingSystems
=> Migrate SupportedOperatingSystems page to Markdown.

docs/archive/OSGReleaseSeries, docs/release/release_series.md, mkdocs.yml
Replaces https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/OSGReleaseSeries
=> Migrate OSGReleaseSeries to Markdown

docs/css/extra.css
=> Add code highlighting, wider content, and scrollbars for code blocks

docs/common/yum.md
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/YumRepositories
Note, this is an update to a document that already existed, so no new menu entry.
=> Update yum repos

docs/common/yum-basics.md, docs/common/yum.md, docs/release/yum-basics.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/YumRpmBasics
=> Adding yum basics page

archive/AutomatedTests
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/AutomatedTests
Conversion: https://github.com/opensciencegrid/osg-test/pull/93
=> Archive AutomatedTests

archive/InstallRsvGlideinwmsTester, docs/monitoring/rsv-gwms-tester.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallRsvGlideinwmsTester
=> Install rsv gwms tester

docs/css/extra.css
We have the same fix in the technology docs.
=> Fix fixed-width font height

docs/other/lcmaps-voms-authentication.md
- Removing edg-mkgridmap step shouldn't be a sub-bullet
- Add a restarting the CE step for good measure
- Change the note to a warning
=> Fixups to the edg-mkgridmap transition steps

archive/ReSSClassadExistsProbe
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/ReSSClassadExistsProbe
=> archive ReSSClassadExistsProbe

archive/InstallCertScripts, archive/InstallCleanupScripts, archive/InstallComputeElement, archive/InstallCondor
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallCertScripts
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallCleanupScripts
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallComputeElement
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallCondor
---
=> archive InstallGuides (various)

archive/TroubleShootingCEMonGIP, archive/TroubleshootingComputeElement, archive/TroubleshootingCondorFirewalls, archive/TroubleshootingExpiredProxy, archive/TroubleshootingFaq, archive/TroubleshootingMissingQueueCommand
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleShootingCEMonGIP
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleshootingComputeElement
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleshootingCondorFirewalls
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleshootingExpiredProxy
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleshootingFaq
---
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/TroubleshootingMissingQueueCommand
---
=> archive Troubleshooting (various)

archive/Release300u0
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release300u0
=> archive Release300u0

archive/Release300u1
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release300u1
=> archive Release300u1

archive/Release300u2
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release300u2
=> archive Release300u2

archive/Release3010
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3010
=> archive Release3010

archive/Release303
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release303
=> archive Release303

archive/Release304
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release304
=> archive Release304

archive/Release305
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release305
=> archive Release305

archive/Release306
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release306
=> archive Release306

archive/Release307
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release307
=> archive Release307

archive/Release309
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release309
=> archive Release309

archive/Release310
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release310
=> archive Release310

archive/Release311
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release311
=> archive Release311

archive/Release3110
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3110
=> archive Release3110

archive/Release3111
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3111
=> archive Release3111

archive/Release3112
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3112
=> archive Release3112

archive/Release3113
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3113
=> archive Release3113

archive/Release3114
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3114
=> archive Release3114

archive/Release3115
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3115
=> archive Release3115

archive/Release3116
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3116
=> archive Release3116

archive/GumsScalability, archive/InstallGums, docs/compute-element/install-htcondor-ce.md, docs/data/bestman-install.md, docs/data/gridftp.md, docs/monitoring/rsv.md, docs/security/gums-scalability.md, docs/security/install-gums.md, mkdocs.yml
https://twiki.grid.iu.edu/bin/view/Documentation/Release3/InstallGums
https://twiki.grid.iu.edu/bin/view/Documentation/Release3/GumsScalability
These two pages are together because they are related and link to each other.
=> InstallGums and GumsScalability

archive/Release3117
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3117
=> archive Release3117

archive/Release3118
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3118
=> archive Release3118

archive/Release3119
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3119
=> archive Release3119

archive/Release312
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release312
=> archive Release312

archive/Release3120
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3120
=> archive Release3120

archive/Release3121
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3121
=> archive Release3121

archive/Release329
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release329
=> archive Release329

archive/Release328
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release328
=> archive Release328

archive/Release327
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release327
=> archive Release327

archive/Release326
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release326
=> archive Release326

archive/Release325
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release325
=> archive Release325

archive/Release3241
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3241
=> archive Release3241

archive/Release3240
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3240
=> archive Release3240

archive/Release324
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release324
=> archive Release324

archive/Release3239
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3239
=> archive Release3239

archive/Release3238
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3238
=> archive Release3238

archive/Release3237
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3237
=> archive Release3237

archive/Release3236
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3236
=> archive Release3236

archive/Release322
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release322
=> archive Release322

archive/Release3220
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3220
=> archive Release3220

archive/Release3221
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3221
=> archive Release3221

archive/Release3222
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3222
=> archive Release3222

archive/Release3223
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3223
=> archive Release3223

archive/Release3224
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3224
=> archive Release3224

archive/Release3225
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3225
=> archive Release3225

archive/Release3226
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3226
=> archive Release3226

archive/Release3227
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3227
=> archive Release3227

archive/Release3228
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3228
=> archive Release3228

archive/Release3229
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3229
=> archive Release3229

archive/Release323
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release323
=> archive Release323

archive/Release3230
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3230
=> archive Release3230

archive/Release3231
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3231
=> archive Release3231

archive/Release3232
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3232
=> archive Release3232

archive/Release3233
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3233
=> archive Release3233

archive/Release3234
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3234
=> archive Release3234

archive/Release3235
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3235
=> archive Release3235

archive/Release3122
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3122
=> archive Release3122

archive/Release3123
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3123
=> archive Release3123

archive/Release3124
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3124
=> archive Release3124

archive/Release3125
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3125
=> archive Release3125

archive/Release3126
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3126
=> archive Release3126

archive/Release3127
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3127
=> archive Release3127

archive/Release3128
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3128
=> archive Release3128

archive/Release3129
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3129
=> archive Release3129

archive/Release313
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release313
=> archive Release313

archive/Release3130
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3130
=> archive Release3130

archive/Release3131
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3131
=> archive Release3131

archive/Release3132
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3132
=> archive Release3132

archive/Release3133
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3133
=> archive Release3133

archive/Release3134
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3134
=> archive Release3134

archive/Release3135
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3135
=> archive Release3135

archive/Release3136
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3136
=> archive Release3136

archive/Release3137
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3137
=> archive Release3137

archive/Release3138
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3138
=> archive Release3138

archive/Release3139
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3139
=> archive Release3139

archive/Release314
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release314
=> archive Release314

archive/Release3140
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3140
=> archive Release3140

archive/Release3141
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3141
=> archive Release3141

archive/Release3142
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3142
=> archive Release3142

archive/Release3143
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3143
=> archive Release3143

archive/Release3144
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3144
=> archive Release3144

archive/Release3145
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3145
=> archive Release3145

archive/Release3146
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3146
=> archive Release3146

archive/Release315
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release315
=> archive Release315

archive/Release316
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release316
=> archive Release316

archive/Release317
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release317
=> archive Release317

archive/Release318
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release318
=> archive Release318

archive/Release319
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release319
=> archive Release319

archive/Release320
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release320
=> archive Release320

archive/Release321
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release321
=> archive Release321

archive/Release3210
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3210
=> archive Release3210

archive/Release3211
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3211
=> archive Release3211

archive/Release3212
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3212
=> archive Release3212

archive/Release3213
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3213
=> archive Release3213

archive/Release3214
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3214
=> archive Release3214

archive/Release3215
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3215
=> archive Release3215

archive/Release3216
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3216
=> archive Release3216

archive/Release3217
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3217
=> archive Release3217

archive/Release3218
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3218
=> archive Release3218

archive/Release3219
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Release3219
=> archive Release3219

archive/Contrib, docs/release/contrib.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/Contrib
=> migrate Contrib -> release/contrib.md

archive/OsgCaCertsUpdater, docs/common/ca.md, docs/common/osg-ca-certs-updater.md, docs/install-overview.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/OsgCaCertsUpdater
=> Documentation.Release3.OsgCaCertsUpdater

mkdocs.yml
Somehow the 'install docs - other' section got duplicated
=> Remove duplicate docs in the ToC

archive/InstallBestmanXrootdSE, docs/data/bestman-overview.md, docs/data/install-bestman-xrootd.md, docs/install-overview.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallBestmanXrootdSE#Screen_Dump_of_Install_Procedure
=> Bestman xrootd SE

archive/InstallXrootdClient, docs/data/install-xroot-client.md, mkdocs.yml
https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/InstallXrootdClient
=> Install xrootd client pull request

docs/security/lcmaps-voms-authentication.md
=> Add info about all-fqans option to LCMAPS VOMS docs

mkdocs.yml
https://github.com/mkdocs/mkdocs/issues/1321#issuecomment-338818134
=> Fix 'Edit on GitHub links' (closing slashes required)

docs/common/help.md, docs/compute-element/troubleshoot-htcondor-ce.md, docs/data/install-hadoop-2-0-0.md, docs/index.md, docs/release/yum-basics.md, docs/site-planning.md
It is believed to be more self-evident what one would find at `help@opensciencegrid.org`.
=> Change goc@ to help@ for support-related requests.

docs/security/host-certs.md
=> Update host ca document

docs/release/3.3/release-3-3-30.md, docs/release/3.4/release-3-4-5.md
The changes pre-approved by Brian Lin
=> Update links for today's HTCondor release

docs/data/external-oasis-repos.md
PR for internal instructions: https://github.com/opensciencegrid/operations/pull/99
=> Remove internal OSG instructions

docs/release/3.3/release-3-3-29-3.md, docs/release/3.3/release-3-3-30-2.md, docs/release/3.3/release-3-3-30-3.md, docs/release/3.3/release-3-3-30.md, docs/release/3.4/release-3-4-4-3.md, docs/release/3.4/release-3-4-5-2.md, docs/release/3.4/release-3-4-5-3.md, docs/release/notes.md, mkdocs.yml
I have clicked on the links to JIRA and koji and the IGTF change log. All looks in order to me.
=> Add release notes for 3.3.30-3 and 3.4.5-3

docs/worker-node/install-singularity.md
Hopefully will help folks figure out the CMS details that don't belong in the OSG docs.
=> Add reference to the CMS-specific instructions for Singularity.

docs/worker-node/install-singularity.md
This is being added on @bbockelm's request, in an attempt to help to ease the security concerns of those who have not yet installed singularity.
=> add discussion of disabling image file mounts

docs/worker-node/install-singularity.md
I'm wondering if it is OK to leave step 4 marked "(Optional)".
=> Add warning of exploit of unprivileged network namespaces

docs/security/host-certs.md, mkdocs.yml
=> Host cert doc updates

docs/other/schedd-filebeats.md
Som order changes after feedback from Mats.
=> Some order changes and missing the enabled

docs/data/install-xrootd.md
These are some formatting fixes I wrote last time I started to update this doc.
=> XRootD install doc formatting fixes

docs/common/ca.md, docs/compute-element/install-htcondor-ce.md
A lot of duplicate info removed but it's possible that I may have gotten carried away...
=> CA doc content review (SOFTWARE-3070)

docs/release/3.3/release-3-3-32.md, docs/release/3.4/release-3-4-8.md, docs/release/notes.md, mkdocs.yml
Lists of packages and RPMs need to be updated before this is reviewed/merged
=> Add release notes for 3.3.32 and 3.4.8

docs/compute-element/troubleshoot-htcondor-ce.md
Formatting and minor updates for CE troubleshooting doc
=> CE troubleshooting updates for SOFTWARE-3079

docs/security/lcmaps-voms-authentication.md
Since we may link GUMS users directly to this section
=> Clarify LCMAPS VOMS must be installed+configured on the clients

docs/common/ca.md
https://opensciencegrid.github.io/docs-itb/common/ca/
=> Fix table formatting

docs/index.md
Minor changes:
- Fix location of search bar
- Make note of 3.4 release, and a more general statement to update between them.
Major Changes:
- Add an ordered list of items to install an OSG site.
- Change order so that installation of CE is before WN.
=> Update the docs index page

docs/data/install-xrootd.md, docs/security/host-certs.md, docs/security/lcmaps-voms-authentication.md
@zvada could you also take a look at this?
@matyasselmeci please run the instructions to set up a standalone xrootd server with xrootd-lcmaps
=>  Document xrootd-lcmaps usage with LCMAPS VOMS (SOFTWARE-2949) 

docs/compute-element/install-htcondor-ce.md, docs/data/frontier-squid.md, docs/data/load-balanced-gridftp.md, docs/release/release_series.md, docs/security/lcmaps-voms-authentication.md, docs/worker-node/install-cvmfs.md, docs/worker-node/install-singularity.md
From the review of the HTCondor-CE installation doc*
=> Address comments from HTCondor-CE installation review (SOFTWARE-3066) 

docs/other/install-gwms-frontend.md
Hold off on merging this until https://jira.opensciencegrid.org/browse/SOFTWARE-2967 is released
@mambelli I've streamlined some of the service information, please review
=> Document usage of gWMS proxy renewal service (SOFTWARE-2967) 

mkdocs.yml
I had trouble finding the install doc for Squid because nothing in our table of contents said Squid.
=> Update TOC to include Frontier-Squid

docs/compute-element/job-router-recipes.md, docs/compute-element/troubleshoot-htcondor-ce.md
[This ticket](https://ticket.opensciencegrid.org/36352) made me revisit our out-of-date troubleshooting docs
=> Update the job router 30 min timeout hold message

docs/security/lcmaps-voms-authentication.md
Fix formatting and combine VO recommendations into the step that tells
users to create the appropriate accounts.
cc: @jdost321
=> Add recommendation to add mis account

docs/other/install-gwms-frontend.md
Noticed by Lorena, the new gWMS dev
=> Fix the automated proxy renewal service for EL7

docs/data/external-oasis-repos.md
Also use a HERE document for input, the input line was too long.
=> Add UNL addresses to .htaccess

docs/security/lcmaps-voms-authentication.md
I banged this out really quickly during my meeting marathon. Feel free to push directly to my branch if there's anything that needs fixing!
=> Add documentation for improper gridftp version

docs/security/host-certs.md
There's some duplication throughout the entire doc with the section I added but that can be dealt with later.
=> InCommon host/service cert request instructions

docs/data/hadoop-overview.md
Fixed list formatting, some minor wording changes, and word wrap at 120/sentence per line
=> Hadoop overview updates for SOFTWARE-3148

docs/common/ca.md, docs/common/help.md, docs/data/bestman-install.md, docs/data/external-oasis-repos.md, docs/other/install-gwms-frontend.md, docs/other/install-voms.md, docs/other/network-performance-toolkit.md, docs/release/3.3/release-3-3-0.md, docs/release/3.3/release-3-3-1.md, docs/release/3.3/release-3-3-2.md, docs/release/3.3/release-3-3-3.md, docs/release/3.3/release-3-3-4.md, docs/release/3.3/release-3-3-5.md, docs/release/3.3/release-3-3-6.md, docs/release/3.3/release-3-3-7.md, docs/release/3.3/release-3-3-8.md, docs/release/3.4/release-3-4-0.md, docs/release/3.4/release-3-4-9.md, docs/security/certificate-management.md, docs/security/host-certs.md
Another round of `opensciencegrid.org` link updates.
=> Modernize links

docs/worker-node/install-singularity.md
A patched kernel is now available.
=> Remove public exploit warning

docs/worker-node/install-singularity.md
Mention that Red Hat does not consider tech previews to be production ready.  Update the dates.
=> Update comments about unprivileged user namespaces

docs/security/host-certs.md
This is WIP - but feel free to give feedback in the mean time.
=> document CSR generation with config and optional SANs (SOFTWARE-3261)

docs/release/release_series.md
=> Add VOMS server retirement instructions (SOFTWARE-3219)

docs/data/frontier-squid.md
This is a follow-on to [SOFTWARE-3310](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3310)
=> make the squid registration documentation more complete

docs/index.md
Already reviewed by TimC and BrianB
=> Add sections for verifying software and site maintenance

docs/worker-node/install-singularity.md
Please merge this when singularity-2.6.0 is released
=> Recommend singularity underlay option

docs/release/supported_platforms.md
After all, that's what we build against.
=> Clarify that the latest sub-release may be required.

docs/data/stashcache/install-origin.md
Bring the doc closer in line with standards and focus on what a VO will need to change in order to use the origin.
=> Overhaul the StashCache origin documentation.

docs/data/stashcache/install-cache.md
This addresses major readability and content issues with the cache
installation document.
It's not obvious one could install either authenticated or public
caches using this documentation.  However, it's a start.
I left several TODO items in the document where it instructed the
human to perform steps that obviously are part of missing packaging.
The StashCache packaging should be fixed and these TODOs eliminated
completely.
=> Begin overhaul of the cache install.

docs/data/stashcache/install-cache.md
It's nice to have all the port requirements in one place.
=> Put port 8443 requirement up front

docs/data/stashcache/install-origin.md
Appears the RPM name in this document was never correct!!!
=> Fix obvious copy/paste errors from the cache docs.

docs/data/stashcache/install-cache.md
My version of #446. There are a bunch of TODOs in there where I don't understand the authfile semantics, so please push fixes.
=> Additional information about stashcache cache Authfiles

docs/data/stashcache/install-cache.md
=> Fix 2 issues in cache document.

docs/compute-element/htcondor-ce-overview.md, docs/data/gridftp.md, docs/data/xrootd/xrootd-authorization.md
It looks like Globus took down their toolkit docs
=> Move Globus Toolkit doc links to the GCT docs

docs/data/stashcache/vo-data.md, docs/data/stashcache/vo-registration.md, mkdocs.yml
This is the VO part of SOFTWARE-3518; putting VO registration in the install-cache and install-origin docs would have made them too big so I split it out.
=> Add doc on StashCache VO registration (SOFTWARE-3518)

docs/worker-node/using-wn-containers.md, mkdocs.yml
Should I add all of the configuration changes required for running jobs in a docker container?  There's a lot of changes.
=> Adding WN container docs

docs/common/registration.md
=> Add policy note about private contact information

docs/security/lcmaps-voms-authentication.md
@sfiligoi had some comments about the clarity about what customizations were possible with the LCMAPS VOMS plugin
=> Clarify lcmaps voms

docs/compute-element/hosted-ce.md, docs/compute-element/htcondor-ce-overview.md, docs/index.md, mkdocs.yml
@edquist things I thought about after the review of your PR
=> Update hosted ce links

docs/other/install-gwms-frontend.md
Instructions for FE admins to configure the shared_port configuration for collectors + ccbs.
=> Instructions for shared port

docs/data/stashcache/overview.md
Source: https://opensciencegrid.org/user-school-2018/#materials/day4/files/osgus18-day4-part3-large-input.pdf
=> Add recommended data size to StashCache overview

docs/compute-element/job-router-recipes.md
This could actually be merged before the release since this is built-in feature of the HTCondor versions that we support
=> Update JR recipes to reflect new multi-line syntax (SOFTWARE-3639)

docs/common/yum.md
And reorganize the Yum repos doc
=> Document priorities for Spacewalk (SOFTWARE-3648)

docs/data/stashcache/install-cache.md, docs/data/stashcache/install-origin.md
This combines #508 and #521; those two documents are closely related and in order to maintain consistency between them, it's helpful to combine them into a single branch.
=> Update StashCache documentation for XCache 1.0.2+ (SOFTWARE-3364)

docs/data/stashcache/install-cache.md
This is the complement of #491 for the cache install doc.
=> Revamp of Stash Cache install doc to match new version

docs/worker-node/install-singularity.md
Fix the incorrect keyword for enabling underlay and disabling overlay.
=> Fix underlay config

docs/compute-element/troubleshoot-htcondor-ce.md
This was a symptom/solution for a tricky problem that @LincolnBryant came across after he moved the spool dir
=> Add troubleshooting info about mismatched spool dirs

docs/worker-node/install-cvmfs.md
=> Eliminate usage of %RED% %ENDCOLOR% in CVMFS install doc

mkdocs.yml
I found it confusing that the CVMFS section of the docs did not have instructions on installing the CVMFS client.
=> Also add link to CVMFS client install to the Data/CVMFS section of the TOC

docs/worker-node/install-singularity.md
For [SOFTWARE-3734](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3734)
=> Update for singularity-3

docs/data/xrootd/xrootd-authorization.md
I was able to get to a pair of the most egregious issues
=> Small XRootD authZ doc fixups

docs/data/xrootd/install-storage-element.md
=> Fixup XRootD SE documentation

docs/release/3.4/release-3-4-31.md
Tim Slauson asked about the package rename, which we sorta highlighted for the condor-python package
=> Highlight the singularity package merge

docs/common/registration.md
`Production: True/False` is defined per resourcegroup.
=> You _need_ a separate resourcegroup for ITB

docs/release/supported_platforms.md
and we will make specific notes on the CVMFS and XRootD pages about the incompatibilities.
=> Strengthen language about old 7.x distros

docs/worker-node/install-singularity.md
https://support.opensciencegrid.org/public/tickets/ebc5f3e2ab78ac9354a0d682d7cc45be2af8ab57417a91651bf05a5dac992b32
=> Fix Singularity image path (FD #27962)

docs/submit/osg-flock.md
=> Overhaul OSG flocking document

docs/data/update-oasis.md
=> Update contact registration requirement

docs/security/host-certs/lets-encrypt.md
=> Rework Let's Encrypt doc; add pre-hook and post-hook info

docs/security/host-certs/lets-encrypt.md
[SOFTWARE-3733]
[SOFTWARE-3733]: https://opensciencegrid.atlassian.net/browse/SOFTWARE-3733
=> Add EL6 instructions for Let's Encrypt

docs/security/user-certs.md
=> Turn usage examples into a bulleted list

docs/data/xrootd/install-cms-xcache.md, mkdocs.yml
This is part of [SOFTWARE-3842](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3842) it is a place to start and I would like some comments from @piperov. 
@brianhlin I am waiting to add a special part if to use  redirector but I would like a review of [PR-75](https://github.com/opensciencegrid/xcache/pull/75).
=> SOFTWARE-3842 Installing a CMS XCache from RPM

docs/index.md
=> We offer resource provisioning services not batch work

docs/data/xrootd/xrootd-authorization.md
=> Fix multiple ACL example

docs/security/lcmaps-voms-authentication.md
https://github.com/opensciencegrid/xrootd-lcmaps/tree/aace3bc0def17f19b2fed7a4c0fae89e74a09594#configuration
=> Fix authzfunparms formatting

docs/data/stashcache/install-cache.md, docs/data/stashcache/install-origin.md
=> Add how to manually set the FQDN for stashcache authfile lookups

docs/data/stashcache/install-origin.md
Origin doesn't use a proxy to authenticate with anything.
=> Origin doesn't need a proxy

docs/worker-node/install-wn-oasis.md
I verified that the paths exist in CVMFS
=> Update OASIS WN versions

docs/compute-element/covid-19.md
=> Use default route names, remove dashes from route names

docs/compute-element/covid-19.md
=> Add item for sites that already have a Hosted CE

docs/compute-element/covid-19.md
https://opensciencegrid.org/docs/compute-element/job-router-recipes/#setting-a-default-batch-queue
=> Fix how users are supposed to set the batch queue

docs/data/xrootd/install-standalone.md, docs/data/xrootd/xrootd-authorization.md
=> Various fixups for the XRootD Standalone install doc

docs/worker-node/install-singularity.md
and add additional option for even better security.
=> Add explanation of docker options for unprivileged singularity

docs/data/update-oasis.md
Clarify how to choose between shared oasis and separate repo, and exactly how to enable shared oasis.
=> Clarify use of shared oasis

docs/common/ca.md
Hi everyone, I'd like to reference this section in an announcement to all OSG sites and VOs today. Please review this ASAP!
=> [URGENT] Add section for verifying up-to-date CAs

docs/release/release_series.md
@jasoncpatton could you look this over, too?
=> Add instructions for updating to HTCondor 8.9.7+

docs/worker-node/install-cvmfs.md, docs/worker-node/install-wn-oasis.md, docs/worker-node/install-wn-tarball.md, docs/worker-node/using-wn-containers.md
=> Add EL8 information to the worker node docs

docs/data/stashcache/run-stash-origin-container.md
For Wesley (https://support.opensciencegrid.org/public/tickets/484383e1df7a17f596516ebca9fa91ddc0109b450c3106b3e61a57d227a89679)
=> Tell users to mount disks to prescribed locations in the origin image (SOFTWARE-4203)

docs/worker-node/install-singularity.md
See [SOFTWARE-4207](https://opensciencegrid.atlassian.net/browse/SOFTWARE-4207)
=> Update singularity doc for el8

docs/data/external-oasis-repos.md
Based on feedback from someone who used the instructions.
=> Clarify a couple of steps in external-oasis-repos

docs/release/3.4/release-3-4-54.md, docs/release/3.5/release-3-5-21.md, docs/release/3.5/release-3-5-22.md, docs/release/notes.md, mkdocs.yml
=> Release notes for 3.5.22 and 3.4.54

docs/compute-element/hosted-ce.md
@jdost321 @lmichael107 site responsibilities doc https://opensciencegrid.org/docs/site-responsibilities/
=> Add section about Hosted CE site responsibilities

docs/compute-element/hosted-ce.md
=> Curiously enough, the Open Science Grid isn't limited to science research!

docs/common/registration.md, docs/compute-element/hosted-ce.md, docs/compute-element/htcondor-ce-overview.md, docs/data/xrootd/install-cms-xcache.md, docs/data/xrootd/install-storage-element.md, docs/other/install-gwms-frontend.md, docs/other/troubleshooting-gratia.md, docs/security/host-certs/digicert.md, docs/security/user-certs.md
These don't appear to be picked up by linkchecker or `mkdocs build --strict`
=> Fix broken image links

docs/other/troubleshooting-gratia.md
=> Gratia Trouble (SOFTWARE-4442)

docs/common/ca.md, docs/common/yum.md, docs/compute-element/install-htcondor-ce.md, docs/data/external-oasis-repos.md, docs/data/frontier-squid.md, docs/data/gridftp.md, docs/data/install-hadoop.md, docs/data/load-balanced-gridftp.md, docs/data/xrootd/install-standalone.md, docs/data/xrootd/install-storage-element.md, docs/other/gsissh.md, docs/other/install-cvmfs-stratum1.md, docs/other/install-gwms-frontend.md, docs/release/supported_platforms.md, docs/security/certificate-management.md, docs/security/host-certs/lets-encrypt.md, docs/security/lcmaps-voms-authentication.md, docs/site-responsibilities.md, docs/site-verification.md, docs/submit/osg-flock.md, docs/worker-node/install-cvmfs.md, docs/worker-node/install-singularity.md
I think this eliminates all the EL6 references in our docs
=> Retire EL6 (SOFTWARE-4383)

docs/data/stashcache/overview.md, mkdocs.yml
=> Separate StashCache docs into a top-level data federation section

docs/submit/osg-flock.md, mkdocs.yml
@rynge @lmichael107 I just added the consultation section, touched up the title, and added some direct links to OSG Connect support documentation. Otherwise, there isn't anything glaringly wrong that we won't be addressing in https://opensciencegrid.atlassian.net/browse/SOFTWARE-4548
=> Review access point doc for glaring issues (SOFTWARE-4547)

docs/compute-element/troubleshoot-htcondor-ce.md
Per some helpful user feedback here: https://support.opensciencegrid.org/a/tickets/67049
=> Point condor_ce_trace users at how to obtain a user cert

docs/common/yum.md
Update to repo-rsync so the syncing is not tied to the repo host.
=> Update to repo-rsync

docs/resource-sharing/user-containers.md
This deals with the change in https://github.com/opensciencegrid/osgvo-docker-pilot/pull/14
=> Add `--scratch /pilot` to singularity command

docs/release/updating-to-osg-35.md, docs/release/updating-to-osg-36.md
I'd like to send an email this week asking that HTCondor-CE admins start upgrading
=> Flesh out HTCondor-CE 5 update sections

docs/release/updating-to-osg-35.md, docs/release/updating-to-osg-36.md
=> Clarify when users need to add custom SCITOKENS mappings

docs/compute-element/hosted-ce.md, docs/site-planning.md
How's this look to you @lmichael107?
=> Clarify Hosted CE cost and local batch prep (SOFTWARE-4510)

mkdocs.yml
Mostly because it's really long now that we moved to nav sections
=> Minor table of contents reorg

docs/common/registration.md
Revamp? Revert? Through discussions with factory ops, we're pushing folks to register their resources like this.
Includes #820: changes were in the same spots but I figured I'd give you a chance to throw tomatoes separately
=> Revamp topology definitions

docs/security/host-certs/digicert.md, docs/security/host-certs/overview.md, mkdocs.yml
They are no longer offering individual IGTF certificates for sale
=> Hide DigiCert instructions

docs/resource-sharing/os-backfill-containers.md
=> Add info on CVMFS and cvmfsexec to the backfill container doc

docs/common/registration.md, docs/compute-element/covid-19.md, docs/other/troubleshooting-gratia.md, docs/site-verification.md
=> Fix GRACC links

docs/resource-sharing/os-backfill-containers.md
(SOFTWARE-4477)
Success here: https://github.com/opensciencegrid/osgvo-docker-pilot/pull/35
=> Update docker commands to reflect reduced caps necessary for CVMFS

docs/resource-sharing/os-backfill-containers.md
=> Revert #874 (SOFTWARE-4477)

docs/other/osg-token-renewer.md
addressed in https://github.com/opensciencegrid/osg-token-renewer/pull/9
=> drop .sh suffix from setup script name (SOFTWARE-4719)

docs/resource-sharing/os-backfill-containers.md, docs/resource-sharing/user-containers.md
- Add section on limiting resource usage to os-backfill-containers doc
- Add section on limiting resources to user-containers.md
=> Limiting resources for the backfill container

docs/release/osg-36.md, docs/release/updating-to-osg-36.md
We should probably hold off on this one until we release XRootD next week
=> Add XRootD multiuser/XrdVoms incompatibility to release notes

docs/compute-element/install-htcondor-ce.md, docs/submit/osg-flock.md
A new OSPool AP user ran into install issues because they didn't have EPEL repos
=> Update install doc reqs

docs/compute-element/install-htcondor-ce.md
@djw8605 I hope this addresses what you were asking for!
=> Flesh out the token auth mapping instructions

docs/release/osg-36.md, docs/release/updating-to-osg-36.md
Let's not merge this until we release this week
=> Update HTCondor gratia instructions (SOFTWARE-4978, SOFTWARE-4979)

docs/release/updating-to-osg-36.md, docs/security/tokens/overview.md
=> Add WebDAV/XRootD support table

docs/release/osg-36.md, docs/release/updating-to-osg-36.md
Noticed this while reviewing OSG 3.6 update instructions
=> Update known bugs in HTCondor-CE

docs/security/tokens/overview.md
Currently they just use HTCondor file transfer with some GridFTP on the backend
=> GlueX doesn't support WebDAV/XRootD

docs/release/osg-36.md, docs/security/tokens/requesting-tokens.md
Brian this is a far as I got. Please have me review it and I can try out examples if provided. I haven't work with tokens before, so I am a good guinea pig I have time today to try things.
=> Start of requesting tokens doc (SOFTWARE-5007)

docs/release/updating-to-osg-36.md
=> Fix URL typo

docs/data/run-frontier-squid-container.md, docs/data/stashcache/run-stash-origin-container.md, docs/data/stashcache/run-stashcache-container.md, docs/resource-sharing/os-backfill-containers.md, docs/resource-sharing/user-containers.md
https://github.com/opensciencegrid/technology/pull/1005
=> Update container references to use OSG 3.6 tags (SOFTWARE-4941)

docs/security/tokens/overview.md
I think IceCube is also a yes?
=> Update CLAS12, EIC, and LIGO VO token acceptance

docs/data/stashcache/install-cache.md
=> Stashcache works on EL8

docs/resource-sharing/os-backfill-containers.md
[FD 69559](https://support.opensciencegrid.org/a/tickets/69559)
=> Fix typo in image name

docs/release/osg-36.md
=> 2022-05-11 Release announcement
